#ifndef OPENMP_OPTICAL_FLOW_CPP_CONFIG_H
#define OPENMP_OPTICAL_FLOW_CPP_CONFIG_H

#define VIDEO_FILENAME R"(C:\cctv052x2004080606x01824.avi)"
#define LOWER_THRESHOLD 10
#define UPPER_THRESHOLD 50

#define MAX_FEATURES 1000

#endif //OPENMP_OPTICAL_FLOW_CPP_CONFIG_H
