#ifndef OPENMP_OPTICAL_FLOW_CPP_CONFIG_H
#define OPENMP_OPTICAL_FLOW_CPP_CONFIG_H

#define VIDEO_FILENAME R"(C:"
#define LOWER_THRESHOLD 10
#define UPPER_THRESHOLD 50

#endif //OPENMP_OPTICAL_FLOW_CPP_CONFIG_H
